name: 'Terraform'

on:
  #push:
    #branches:
    #- main
  #pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.1
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
        args: '-backend-config="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" 
               -backend-config="tenant_id=${{ secrets.ARM_TENANT_ID }}" 
               -backend-config="resource_group_name=TestRg" 
               -backend-config="storage_account_name=sample0456"  
               -backend-config="container_name=dev" 
               -backend-config="key=devgit.tfstate"'

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.1
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
        
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.1
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./terraform"
        
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.2.1
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"

#     - name: Terraform Apply
#       if: github.ref == 'refs/heads/main'
#       uses: hashicorp/terraform-github-actions@master
#       with:
#         tf_actions_version: 1.2.1
#         tf_actions_subcommand: 'apply'
#         tf_actions_working_dir: "./terraform"
